[package]
name = "lintpulse"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.7"
chrono = "0.4"
notify = "8.2"
daemonize = "0.4"
watcher = "0.0.1"
logger = "0.4.0"
glob = "0.3.3"
