
[daemon]
log_file = "lintpulse.log"
watch_path = "./"

[[rules]]
pattern = "*.rs"
lint_command = "cargo clippy --quiet"
format_command = "rustfmt {file}"

[[rules]]
pattern = "*.js"
lint_command = "eslint {file}"
format_command = "prettier --write {file}"

[[rules]]
pattern = "*.py"
lint_command = "flake8 {file}"
format_command = "black {file}"
